# Generated by Django 2.1 on 2020-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGV',
            fields=[
                ('agv_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='AGV编号')),
                ('situation', models.IntegerField(choices=[(1, '良好'), (2, '待修')], verbose_name='设备情况')),
                ('state', models.IntegerField(choices=[(1, '作业'), (2, '空闲')], verbose_name='运行状态')),
            ],
        ),
        migrations.CreateModel(
            name='Quay_crane',
            fields=[
                ('qc_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='岸桥编号')),
                ('sea_state', models.IntegerField(choices=[(1, '作业'), (2, '空闲')], verbose_name='海侧吊具运行状态')),
                ('land_state', models.IntegerField(choices=[(1, '作业'), (2, '空闲')], verbose_name='陆测吊具运行状态')),
                ('situation', models.IntegerField(choices=[(1, '良好'), (2, '待修')], verbose_name='设备情况')),
                ('middle_space', models.IntegerField(verbose_name='中转平台空位')),
                ('weight_max', models.CharField(max_length=10, verbose_name='吊具承重量')),
            ],
        ),
        migrations.CreateModel(
            name='voyage_qc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_plan', models.DateTimeField(null=True, verbose_name='开始占用时间')),
                ('end_plan', models.DateTimeField(null=True, verbose_name='结束占用时间')),
                ('qc', models.ForeignKey(on_delete='岸桥表', to='equipment.Quay_crane')),
            ],
        ),
    ]
