# Generated by Django 2.1 on 2020-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage_qc',
            name='voy',
            field=models.ForeignKey(on_delete='航次表', to='information.Voyage'),
        ),
        migrations.AddField(
            model_name='quay_crane',
            name='voy',
            field=models.ManyToManyField(null=True, through='equipment.voyage_qc', to='information.Voyage'),
        ),
    ]
