# Generated by Django 2.1 on 2020-05-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('iso_no', models.CharField(max_length=11, verbose_name='箱号')),
                ('space', models.CharField(max_length=6, verbose_name='箱位')),
                ('size', models.SmallIntegerField(choices=[(1, '20ft'), (2, '40ft')], verbose_name='尺寸')),
                ('weight', models.CharField(max_length=10, verbose_name='重量')),
                ('special', models.BooleanField(default=False, verbose_name='是否特殊箱')),
                ('type', models.IntegerField(verbose_name='进出口类型')),
                ('agv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.AGV', verbose_name='AGV')),
            ],
            options={
                'verbose_name': '船舶信息表',
                'db_table': 'info_Container',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.AutoField(max_length=6, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('code', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '公共字段表',
                'db_table': 'BaseTable',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VesselInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('en_name', models.CharField(max_length=18, unique=True, verbose_name='英文船名')),
                ('cn_name', models.CharField(max_length=18, verbose_name='中文船名')),
            ],
            options={
                'verbose_name': '船舶信息表',
                'db_table': 'info_vesselInfo',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voy_im', models.CharField(max_length=10, verbose_name='进口航次编号')),
                ('voy_ex', models.CharField(max_length=10, verbose_name='出口航次编号')),
                ('voy_im_state', models.IntegerField(default=0, verbose_name='进口航次状态')),
                ('voy_ex_state', models.IntegerField(default=0, verbose_name='出口航次状态')),
                ('ETB', models.DateTimeField(verbose_name='计划靠泊时间')),
                ('ETD', models.DateTimeField(verbose_name='计划离泊时间')),
                ('ATB', models.DateTimeField(blank=True, default=None, null=True, verbose_name='实际靠泊时间')),
                ('ATD', models.DateTimeField(blank=True, default=None, null=True, verbose_name='实际离泊时间')),
                ('unloading_im', models.BooleanField(default=False, verbose_name='是否卸货完成')),
                ('unloading_ex', models.BooleanField(default=False, verbose_name='是否装货完成')),
                ('current_state', models.IntegerField(default=0, verbose_name='航次当前状态')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.VesselInfo', verbose_name='船信息')),
            ],
            options={
                'verbose_name': '进出口航次表',
                'db_table': 'info_voyage',
            },
        ),
    ]
