# Generated by Django 2.1 on 2020-05-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('plan', '0001_initial'),
        ('job', '0001_initial'),
        ('equipment', '0002_auto_20200503_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Bay_position', verbose_name='贝位'),
        ),
        migrations.AddField(
            model_name='container',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job_unloading', verbose_name='卸箱作业编号'),
        ),
        migrations.AddField(
            model_name='container',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Plan_unloading', verbose_name='卸箱计划编号'),
        ),
        migrations.AddField(
            model_name='container',
            name='qc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Quay_crane', verbose_name='卸箱岸桥'),
        ),
        migrations.AddField(
            model_name='container',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.VesselInfo', verbose_name='船信息'),
        ),
        migrations.AddField(
            model_name='container',
            name='voy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Voyage', verbose_name='进口航次信息'),
        ),
    ]
