# Generated by Django 2.1 on 2020-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200503_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='job',
        ),
        migrations.AddField(
            model_name='container',
            name='state',
            field=models.IntegerField(default=0, verbose_name='装卸状态'),
        ),
    ]
