# Generated by Django 2.1 on 2020-05-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bay_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.CharField(max_length=11, verbose_name='贝位号')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_loading',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='卸船计划号')),
                ('state', models.SmallIntegerField(choices=[(1, '计划'), (2, '执行'), (3, '完成')], default=1, verbose_name='计划完成情况')),
                ('qc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_l_qc', to='equipment.Quay_crane', verbose_name='岸桥信息')),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_l_vessel', to='information.VesselInfo', verbose_name='英文船名')),
                ('voy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_l_voy', to='information.Voyage', verbose_name='出口航次')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_unloading',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='卸箱计划编号')),
                ('state', models.SmallIntegerField(choices=[(1, '计划'), (2, '执行'), (3, '完成')], verbose_name='计划完成情况')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_u_qc', to='equipment.Quay_crane', verbose_name='岸桥信息')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_u_vessel', to='information.VesselInfo', verbose_name='英文船名')),
                ('voy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_u_voy', to='information.Voyage', verbose_name='进口航次')),
            ],
        ),
    ]
