# Generated by Django 2.1 on 2020-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200503_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_unloading',
            name='plan_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='卸箱计划编号'),
        ),
    ]
