# Generated by Django 2.1 on 2020-05-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200503_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_unloading',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='卸船结束时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='job_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='middle_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='至中转平台时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='state_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作业开始时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='state_time_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='岸桥作业开始时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='state_time_sea',
            field=models.DateTimeField(blank=True, null=True, verbose_name='海测吊作业开始时间'),
        ),
    ]
