# Generated by Django 2.1 on 2020-05-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200504_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_unloading',
            name='state_time_after',
        ),
        migrations.RemoveField(
            model_name='plan_unloading',
            name='state_time_sea',
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='end_time_qc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='岸桥作业结束时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='state_time_land',
            field=models.DateTimeField(blank=True, null=True, verbose_name='陆测吊作业开始时间'),
        ),
        migrations.AlterField(
            model_name='plan_unloading',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='卸船作业编号'),
        ),
        migrations.AlterField(
            model_name='plan_unloading',
            name='state_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='卸船作业开始时间'),
        ),
    ]
