# Generated by Django 2.1 on 2020-05-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200503_1957'),
        ('plan', '0006_auto_20200505_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_unloading',
            name='agv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.AGV'),
        ),
    ]
