# Generated by Django 2.0.3 on 2020-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_plan_unloading_agv'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_unloading',
            name='handling_type',
            field=models.IntegerField(default=0, verbose_name='装/卸船类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='start_time_qc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='装船岸桥作业开始时间'),
        ),
        migrations.AddField(
            model_name='plan_unloading',
            name='start_time_sea',
            field=models.DateTimeField(blank=True, null=True, verbose_name='装船海侧吊具作业开始时间'),
        ),
        migrations.AlterField(
            model_name='plan_unloading',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='装/卸船结束时间'),
        ),
        migrations.AlterField(
            model_name='plan_unloading',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='装/卸船作业编号'),
        ),
    ]
